### ISSUE TITLE
Sem issues?

### ISSUE THREAD

**Issue by drbeco** [RafaelRSPX/Robots-RS#1]
?

**Comment by wesleysilas** [comment]
pelo fato de não ter tido muito tempo durante essa semana, fizemos o trabalho nos dias à tarde na faculdade... por isso tenha faltado alguns issues. erramos nesse ponto!

**Comment by RafaelRSPX** [comment]
Infelizmente discutimos pessoalmente professor. Peço desculpas por não ter utilizado a plataforma do git para discussão. Esse erro não será cometido novamente.
