### ISSUE TITLE
Adicionar AUTHORS

### ISSUE THREAD

**Issue by drbeco** [RafaelRSPX/Robots-RS#4]
Adicionar arquivo com autores

**Comment by drbeco** [comment]
Merge no master!

**Comment by RafaelRSPX** [comment]
Arquivo adicionado.

**Comment by RafaelRSPX** [comment]
Adicionei o arquivo AUTHORS no ramo develop e master, porém eu já tinha liberado a versão v1.0 antes de adicionar o arquivo. Por isso, lancei a versão v1.1 no ramo master com o arquivo AUTHORS.

**Comment by wesleysilas** [comment]
otimo rafa!
