### ISSUE TITLE
Melhorias na interface gráfica

### ISSUE THREAD

**Issue by RafaelRSPX** [RafaelRSPX/Robots-RS#6]
Para melhorar a aparência do tabuleiro tentarei alterar a função ```imprimemundo()``` para utilizar os caracteres gráficos da tabela ASCII.

**Comment by RafaelRSPX** [comment]
Inclue as bibliotecas ``` <locale.h>``` e ```<wchar.h>``` para adpatar o programa ao tipo UTF-8. Falta incluir todos os ```#define``` para os caracteres das bordas.

**Comment by RafaelRSPX** [comment]
Alterei o makefile e incluir a caracteristica ```-std=c99``` no ```CFLAGS``` para compilar o código.

**Comment by wesleysilas** [comment]
beleza... ficou muito melhor

**Comment by wesleysilas** [comment]
Adicionei no códigos os seguintes defines:
```
#define UL L'\u2518' 
#define DL L'\u2510' 
#define DR L'\u250c' 
#define UR L'\u2514' 
#define VH L'\u253c' 
#define HH L'\u2500' 
#define VR L'\u251c' 
#define VL L'\u2524' 
#define UH L'\u2534' 
#define DF L'\u252c' 
#define VV L'\u2502' 
```
Seguindo o ex28.c para que o programa desenhe o tabuleiro com o padrão UTF-8.

**Comment by wesleysilas** [comment]
Também fiz as alterações na função ``` imprimehud``` para a impressão.

**Comment by RafaelRSPX** [comment]
Ok. Irei testar para ver se tem algum problema.

**Comment by RafaelRSPX** [comment]
Tava testando o programa no windows também e ví que ele não tava compilando por causa da condição dos defines
```
#ifdef __linux__
#define UL L'\u2518' /* ┘ */
#define DL L'\u2510' /* ┐ */
#define DR L'\u250c' /* ┌ */
#define UR L'\u2514' /* └ */
#define VH L'\u253c' /* ┼ */
#define HH L'\u2500' /* ─ */
#define VR L'\u251c' /* ├ */
#define VL L'\u2524' /* ┤ */
#define UH L'\u2534' /* ┴ */
#define DF L'\u252c' /* ┬ */
#define VV L'\u2502' /* │ */

#else
#error "Programa incompativel com o sistema"
#endif
```

**Comment by RafaelRSPX** [comment]
Testei sem a condição e vi que o programa imprime o tabuleiro com caracteres diferentes,  mas o programa mesmo assim é compatível com o sistema. Eu vou tirar essa condição e testar o programa.

**Comment by RafaelRSPX** [comment]
Retirei a condição e mandei para o git. Tudo finalizado.
